language: generic
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.npm
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes
- conda config --set quiet yes
- conda config --set changeps1 no
- conda config --add channels bokeh
- conda config --add channels conda-forge
- conda info -a
- conda install conda-build nodejs selenium jupyterlab notebook geckodriver firefox
- npm set progress false
- npm install -g npm
- conda build conda.recipe/
script:
- npm install
- npm run build
#- npm run lint
- jupyter labextension install .
- jupyter lab clean
- jupyter labextension link .
- python -m jupyterlab.selenium_check
